Варіант 22

In [1]:
import numpy as np

# Завдання 1

Створіть одновимірний масив (вектор) зі значеннями 𝑒^𝑥 для кожного натурального числа x, починаючи з 1, та виведіть його значення.

In [15]:
n = int(input("Enter the number of iterations:"))
x = np.arange(1, n + 1)

exp_values = np.exp(x)

print(f"Exponential values: {exp_values} for {x}")

Exponential values: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ] for [1 2 3 4 5]


# Завдання 2

Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його тангенсами кожного натурального числа, починаючи з 1, та виведіть його значення.

In [14]:
m_3_3 = np.arange(1, 10).reshape(3, 3)
m_tn  = np.tan(m_3_3)

print(m_tn)

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


# Завдання 3

Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від -1 до 1 та виведіть непарні числа.

In [32]:
m_3_3       = np.random.uniform(-1, 1, (3, 3))
odd_numbers = m_3_3.astype(int) % 2 != 0

print(f"An 3x3 array of random real numbers:\n {m_3_3}")
print(f"Odd integers:\n {m_3_3[odd_numbers]}")

A 3x3 array of random real numbers:
 [[ 0.06485861  0.29020712  0.22614171]
 [-0.53658605  0.61811263 -0.24718989]
 [ 0.7704349  -0.94639435  0.83350402]]
Odd integers:
 []


Оскільки числа в матриці згенеровані від -1 до 1, то непарних чисел немає. 
Спробуємо взяти більший інтревал між числами, наприклад від -5 до 5:

In [33]:
m_3_3       = np.random.uniform(-5, 5, (3, 3))
odd_numbers = m_3_3.astype(int) % 2 != 0

print(f"An 3x3 array of random real numbers:\n {m_3_3}")
print(f"Odd integers:\n {m_3_3[odd_numbers]}")

An 3x3 array of random real numbers:
 [[-3.21568572 -1.10115662  0.96915689]
 [-1.10349504 -1.16116209  1.0121477 ]
 [ 0.74613503  2.11434964  2.09669786]]
Odd integers:
 [-3.21568572 -1.10115662 -1.10349504 -1.16116209  1.0121477 ]


# Завдання 4

Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -0.8 до 0.8 та виведіть його значення.

In [34]:
m_4_4 = np.random.uniform(-0.8, 0.8, (4, 4))

print(f"An 4x4 array of random real numbers:\n {m_4_4}")

An 4x4 array of random real numbers:
 [[ 0.53224076  0.69735477 -0.22160289 -0.38127726]
 [-0.06574332 -0.22878989  0.58171428 -0.51063831]
 [-0.09403292  0.16338254  0.40347807 -0.5111237 ]
 [ 0.28668682  0.44376712  0.13671958 -0.68913983]]


# Завдання 5

Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 5 до 15 та виконайте на них поелементні операції додавання, віднімання та множення.

In [43]:
arr_1 = np.random.randint(5, 16, size = 6)
arr_2 = np.random.randint(5, 16, size = 6)

addition       = arr_1 + arr_2
subtraction    = arr_1 - arr_2
multiplication = arr_1 * arr_2

print(f"Array 1: {arr_1}\nArray 2: {arr_2}")
print(f"Addition: {addition}")
print(f"Subtraction: {subtraction}")
print(f"Multiplication: {multiplication}")

Array 1: [10 10  6 15  8 13]
Array 2: [ 5  8  5 10  6  7]
Addition: [15 18 11 25 14 20]
Subtraction: [5 2 1 5 2 6]
Multiplication: [ 50  80  30 150  48  91]


# Завдання 6

Створіть дві матриці 4x4, заповніть їх довільними цілими числами від -6 до 6 та знайдіть їх добуток.

In [42]:
m_1 = np.random.randint(-6, 7, size = (4, 4))
m_2 = np.random.randint(-6, 7, size = (4, 4))

product_m = np.dot(m_1, m_2)

print(f"Matrix 1:\n{m_1}\n Matrix 2:\n{m_2}")
print(f"Product of matrices:\n{product_m}")

Matrix 1:
[[ 0  3 -6 -1]
 [ 6 -1  3 -4]
 [ 3  2  4 -4]
 [-6 -5 -6  3]]
 Matrix 2:
[[-6  1 -6  4]
 [-2 -2  3  4]
 [-6 -3 -2 -4]
 [-1 -1  5  6]]
Product of matrices:
[[ 31  13  16  30]
 [-48   3 -65 -16]
 [-42  -9 -40 -20]
 [ 79  19  48  -2]]


# Завдання 7

Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 8 та перемножте їх між собою.

In [46]:
m_1 = np.random.randint(1, 9, size = (3, 2))
m_2 = np.random.randint(1, 9, size = (2, 2))

product_m = np.dot(m_1, m_2)

print(f"Matrix 1:\n{m_1}\n Matrix 2:\n{m_2}")
print(f"Product of matrices:\n{product_m}")

Matrix 1:
[[8 5]
 [3 2]
 [6 8]]
 Matrix 2:
[[4 4]
 [3 3]]
Product of matrices:
[[47 47]
 [18 18]
 [48 48]]


# Завдання 8

Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 8 та знайдіть її обернену матрицю.

In [47]:
m = np.random.randint(1, 9, size = (3, 3))

inverse_m = np.linalg.inv(m)

print(f"Matrix:\n{m}")
print(f"Inverse matrix:\n{inverse_m}")

Matrix:
[[1 4 7]
 [2 8 6]
 [5 6 3]]
Inverse matrix:
[[ 0.10714286 -0.26785714  0.28571429]
 [-0.21428571  0.28571429 -0.07142857]
 [ 0.25       -0.125       0.        ]]


# Завдання 9

Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та транспонуйте її.

In [49]:
m = np.random.uniform(-1, 1, size = (4, 4))

transposed_m = m.T

print(f"Matrix:\n{m}")
print(f"Transposed matrix:\n{transposed_m}")

Matrix:
[[-0.58070779  0.79533807 -0.10258844 -0.9365585 ]
 [ 0.5053437  -0.53560708 -0.12150438 -0.55375013]
 [-0.17792932  0.60204194  0.93522856 -0.92478591]
 [-0.27419371 -0.88770144  0.76658956  0.30274592]]
Transposed matrix:
[[-0.58070779  0.5053437  -0.17792932 -0.27419371]
 [ 0.79533807 -0.53560708  0.60204194 -0.88770144]
 [-0.10258844 -0.12150438  0.93522856  0.76658956]
 [-0.9365585  -0.55375013 -0.92478591  0.30274592]]


# Завдання 10

Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [51]:
m = np.random.uniform(0, 1, size = (3, 4))
v = np.random.randint(1, 11, size = (4, 1))

product_m_v = np.dot(m, v)

print(f"Matrix 3x4:\n{m}")
print(f"Vector 4x1:\n{v}")
print(f"Matrix product by vector:\n{product_m_v}")

Matrix 3x4:
[[0.64285393 0.72760065 0.53589742 0.92258764]
 [0.87660641 0.4984403  0.43010927 0.15924944]
 [0.22263858 0.95538716 0.35551849 0.44456473]]
Vector 4x1:
[[3]
 [8]
 [3]
 [8]]
Matrix product by vector:
[[16.73776043]
 [ 9.18166502]
 [12.93408627]]


# Завдання 11

Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [52]:
m = np.random.randint(1, 11, size = (2, 3))
v = np.random.uniform(0, 1, size = (3, 1))

product_m_v = np.dot(m, v)

print(f"Matrix 2x3:\n{m}")
print(f"Vector 3x1:\n{v}")
print(f"Matrix product by vector:\n{product_m_v}")

Matrix 2x3:
[[ 6 10  7]
 [ 9  8  6]]
Vector 3x1:
[[0.74696978]
 [0.60927716]
 [0.6722143 ]]
Matrix product by vector:
[[15.2800903 ]
 [15.63023102]]


# Завдання 12

Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 3 та знайдіть суму всіх елементів другої матриці.

In [53]:
m_1 = np.random.randint(1, 4, size = (3, 3))
m_2 = np.random.randint(1, 4, size = (3, 3))

sum_m_2 = np.sum(m_2)

print(f"Matrix 1:\n{m_1}\n Matrix 2:\n{m_2}")
print(f"Sum of all the elements of matrix 2:\n{sum_m_2}")

Matrix 1:
[[1 2 1]
 [1 2 3]
 [1 2 1]]
 Matrix 2:
[[2 3 3]
 [2 2 2]
 [1 2 3]]
Sum of all the elements of matrix 2:
20


# Завдання 13

Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та знайдіть суму їх елементів.

In [54]:
m_1 = np.random.randint(1, 6, size = (3, 3))
m_2 = np.random.randint(1, 6, size = (3, 3))

sum_m_1 = np.sum(m_1)
sum_m_2 = np.sum(m_2)

print(f"Matrix 1:\n{m_1}\n Matrix 2:\n{m_2}")
print(f"Sum of all the elements of matrix 1:\n{sum_m_1}")
print(f"Sum of all the elements of matrix 2:\n{sum_m_2}")

Matrix 1:
[[4 2 4]
 [4 2 5]
 [4 2 5]]
 Matrix 2:
[[2 2 1]
 [4 4 5]
 [5 1 1]]
Sum of all the elements of matrix 1:
32
Sum of all the elements of matrix 2:
25


# Завдання 14

Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму елементів на головній діагоналі.

In [55]:
m = np.random.randint(1, 11, size = (3, 3))

diag_sum = np.trace(m)

print(f"Matrix:\n{m}")
print(f"Sum of all the elements of matrix on the main diagonal:\n{diag_sum}")

Matrix:
[[ 5 10  4]
 [10  1  5]
 [ 7  9  9]]
Sum of all the elements of matrix on the main diagonal:
15


# Завдання 15

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить добуток елементів кожного стовпця матриці.

In [62]:
m = np.random.uniform(-1, 1, size = (3, 3))

column_products_v = np.prod(m, axis = 0).reshape(-1 ,1)

print(f"Matrix 3x3:\n{m}")
print(f"A column vector with products of elements of each column::\n{column_products_v}")

Matrix 3x3:
[[-0.57324626  0.50825602  0.88763618]
 [ 0.44465954 -0.25507555 -0.698545  ]
 [-0.09197146 -0.91854308  0.5556828 ]]
A column vector with products of elements of each column::
[[ 0.02344347]
 [ 0.11908331]
 [-0.34455324]]


# Висновок

У даній роботі я згадала як працювати із Jyputer Notebook, Git. Також, згадала основні дії з матрицями та векторами.